#ifndef SETTINGS_H
#define SETTINGS_H

//#define SEND_RAW_GYRO
//#define SEND_RAW_ACC

#define USE_USART3

//Settings for sensors fusion

#define SETTINGS_SENSFUS_PERFORM_FILTRATION

#define SETTINGS_SENSFUS_SIZE_FILTER_ACCEL 5
#define SETTINGS_SENSFUS_SIZE_FILTER_GYRO 5

//#define SETTINGS_SENSFUS_FILTER_MEDIAN //if commented, average will be used
#define SETTINGS_SENSFUS_MEDIAN_POSITION 3 //ignired, if avergage is used

#define SETTINGS_SENSFUS_SEND_FILTERED_ACC
#define SETTINGS_SENSFUS_SEND_FILTERED_GYRO

#define SETTINGS_SENSFUS_CALIBRATE_GYRO
#define SETTINGS_SENSFUS_CALIBRATE_ACC

#define SETTINGS_SENSFUS_CALIBRATION_CYCLES 100

//Settings for messenger

//#define SETTINGS_MSNR_1BYTE
#define SETTINGS_MSNR_3BYTE
//#define SETTINGS_MSNR_5BYTE

#endif /*SETTINGS_H*/